name: generate native image and release

# okay, this was copy pasted from many places and I do not really pretend to understand what I am doing, but many thanks to the authors of:
# https://github.com/remkop/picocli-native-image-demo
# for the native image guide, as well as the authors of all the used actions and their many useful examples

# feel free to use any added value of this file under CC-0

# also, can we please stop programming in YAML?

on: 
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

defaults:
  run:
    shell: bash
jobs:
  build-native-image:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # if these are updated, also update the references below
        os: [macOS-12, ubuntu-22.04, windows-2022]
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
        continue-on-error: true
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1'
          java-version: '19'
          components: 'native-image,js'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: coursier/setup-action@v1
        with:
          apps: sbt sbtn
      - name: generate native image
        run: |
          sbtn stageJars
          native-image --enable-preview --class-path "jvm/target/jars/*" viscel.Viscel
          rm viscel*build_artifacts.txt
      - name: create & copy static files
        run: |
          sbtn vbundle
          mkdir -p bundle
          cp -r target/resources/static bundle/
          cp viscel* bundle/
      - name: Publish artifact
        uses: actions/upload-artifact@master
        with:
          name: viscel-${{ matrix.os }}
          path: bundle
  release-artifact:
    name: Upload Release Asset
    runs-on: ubuntu-22.04
    needs: [build-native-image]
    steps:
      - uses: actions/download-artifact@v2
      - name: fix executable bit and create archives
        run: |
          chmod +x viscel-ubuntu-22.04/viscel
          chmod +x viscel-macOS-12/viscel
          zip -r viscel-windows.zip viscel-windows-2022/*
          tar -zcvf viscel-linux.tar.gz viscel-ubuntu-22.04/*
          tar -zcvf viscel-macOS.tar.gz viscel-macOS-12/*
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset Windows
        id: upload-release-asset-windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: viscel-windows.zip
          asset_name: viscel-windows.zip
          asset_content_type: application/zip
      - name: Upload Release Asset Ubuntu
        id: upload-release-asset-ubuntu
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: viscel-linux.tar.gz
          asset_name: viscel-linux.tar.gz
          asset_content_type: application/gzip
      - name: Upload Release Asset macOS
        id: upload-release-asset-macos
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: viscel-macOS.tar.gz
          asset_name: viscel-macOS.tar.gz
          asset_content_type: application/gzip
