name: tests

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/setup-java@v1
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: run tests
        run: |
          sbt compile test
