name: tests

on: [push]

jobs:
  build-windows:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v1
      - uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '20.1.0.java11'
      - name: install known good sbt version
        run: |
          choco install sbt --force --version 1.3.10
      - name: run tests
        run: |
          sbt test
