name: Scala CI

on: [push, pull_request]

jobs:
  # build:

  #   runs-on: windows-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up JDK 11
  #     uses: actions/setup-java@v1
  #     with:
  #       java-version: 11
  #   - name: Run tests
  #     run: sbt test stage
  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016]

    steps:
      - uses: actions/checkout@v1
      - uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '20.1.0.java11'
      - run: java -version
      - name: install native image
        shell: cmd
        run: gu install native-image
      - run: native-image --version
      - name: where is this thing?!
        shell: cmd
        run: where native-image
      - name: Set up Visual C Build Tools Workload for Visual Studio 2017 Build Tools
        run: |
          choco install visualstudio2017-workload-vctools
      - name: set env variables and run the build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          set GRAALVM_NATIVE_IMAGE_PATH=C:\hostedtoolcache\windows\GraalVM\20.1.0-java11\x64\bin\native-image.cmd
          sbt nativeImage
      - name: Publish artifact
        uses: actions/upload-artifact@master
        with:
          name: viscel.exe
          path: target/graalvm-native-image
