name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: fetch sbt
      run: curl -Ls https://git.io/sbt > sbt
    - name: Run a multi-line script
      run: ./sbt test
